[package]
name = "rust_http2_test"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "*", features = ["http2", "native-tls-alpn"] }
tracing = "*"
tracing-subscriber = { version = "*", features = ["fmt"] }
tokio = { version = "1.43", features = ["full"] }
